url: "https://duleorlovic.github.com"
baseurl: "tailwind_play_responsive_dark_mode"
title: "" # the name of your site, e.g. ACME Corp.
plugins:
  - jekyll-postcss

postcss:
  # disable cache for Tailwind CSS JIT engine so we do not need to restart jekyll
  cache: false
